title: Default Page
icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu


pages: false

tabs:

  # content tab
  content:
    label: Content
    icon: text
    columns:

      # intro one
      column2:
        width: 2/2
        sections:
          content2:
            type: fields
            fields:
                text:
                    label: Text
                    type: textarea
                    size: medium
                    buttons: true
                blocks:
                    label: Page Blocks
                    type: builder
                    columns: 1 # Optional. If set to 2 or more, the builder blocks will be placed in a grid.
                    max: 10 # Optional. Limits the number of builder blocks that can be added.
                    fieldsets:
                        

  # seo tab
  seo:
    label: SEO
    icon: search
    fields:
      seoTitle:
        label: SEO Title
        type: text
      seoDescription:
        label: SEO Description
        type: text

  # Files tab
  filesTab:
    label: Files
    icon: add
    sections:
      filesSection:
        headline: Files
        type: files
        layout: cards
        size: small
        template: default

