title: Site
unlisted: true

columns:
 - width: 1/3
     sections:
      pages:
        type: pages
        headline: Menu Pages
        status: listed
 - width: 1/3
     sections:
      hidden:
        type: pages
        headline: Pages
        status: unlisted
 - width: 1/3
     sections:
      drafts:
        type: pages
        headline: Drafts
        status: draft
 - width: 2/2
   fields:
    settings:
     label: Submission Settings
     type: headline
     numbered: false
     width: 2/2 
    submissionsOpen:
     label: Submissions on or off?
     type: toggle 
     width: 2/2   
     help: 'This setting will be overridden by any automation set below'
    automateSubmissions:
     label: Automate submission times?
     type: toggle 
     width: 1/4   
    openTime:
     label: Open From
     type: time
     width: 1/4   
    closeTime:
     label: Closed From
     type: time  
     width: 1/4   
    timeDifference:
     label: Time difference (from GMT)
     type: number
     min: -12
     max: 14  
     width: 1/4        
    strictModeration:
     label: Strict Moderation
     type: toggle 
     width: 2/2   
     help: 'Strict moderation will put ALL names in the moderation queue'              
 - width: 2/2
   fields:
    footer:
     label: Site Footer
     type: headline
     numbered: false
     width: 2/2
    footerTitle:
     label: Footer Title
     type: text
    footerCallToAction:
     label: Call to action
     type: textarea
     buttons: false
    footerNavigation:
     label: Footer Navigation
     type: pages
    mailingListSignUpTitle:
     label: Mailing List Sign Up Title
     type: text
    mailingListSignUpText:
     label: Mailing List Sign Up Text
     type: textarea
     buttons: false
    mailingListSignUpURL:
     label: Mailing List Sign Up URL
     type: text
     buttons: false
     help: 'Used to generate the mailchimp sign up form'
    logos:
        label: Logo Rows
        type: structure
        fields:
          title:
            label: Row Title
            type: textarea
          logoImages:
            label: Logo Files
            type: files
            layout: cards
            size: small
            uploads:
              template: logo
            image:
              ratio: 1/1
              back: white